---
version: "3"
services:
  movie:
    image: paytm:v1
    ports:
      - 1000:80
    volumes:
      - volume1
    deploy:
      replicas: 4
  train:
    image: paytrain:v1
    volumes:
      - volume2
    ports:
      - 8001:80
    deploy:
      replicas: 4
  recharge:
    image: paymovie:v1
    volumes:
      - volume3
    ports:
      - 8002:80
    deploy:
      replicas: 4
